### ISSUE TITLE
can't run xclock, missing symbols

### ISSUE THREAD

**Issue by X547** [waddlesplash/xlibe#1]
```
runtime_loader: /boot/system/lib/libXext.so.6.4.0: Could not resolve symbol '_XUnlockMutex_fn'
runtime_loader: /boot/system/lib/libXext.so.6.4.0: Could not resolve symbol '_Xglobal_lock'
runtime_loader: /boot/system/lib/libXext.so.6.4.0: Could not resolve symbol 'XAddExtension'
```

**Comment by waddlesplash** [comment]
Not surprising, I haven't tested with a lot of the wrapper libraries. And I think xclock requires Xaw, which I know does not work (or even build) yet.

**Comment by X547** [comment]
Xaw from HaikuPorts works with XSDL server.

**Comment by waddlesplash** [comment]
It appears Xext interacts with the server directly. It won't be usable with BeXlib, instead whatever it does will have to be reimplemented here.

**Comment by waddlesplash** [comment]
Now builds and starts. However there are some artifacts: 
![image](https://user-images.githubusercontent.com/2175324/145926803-32de5a73-b921-41b8-bc8c-d615d04745ea.png)

**Comment by X547** [comment]
```
UNIMPLEMENTED: XSetLocaleModifiers
Warning: X locale modifiers not supported, using default
UNIMPLEMENTED: XSynchronize
UNIMPLEMENTED: XAddConnectionWatch
Warning: Unable to load any usable ISO8859 font
UNIMPLEMENTED: int XmbTextListToTextProperty(Display*, char**, int, XICCEncodingStyle, XTextProperty*)
UNIMPLEMENTED: int XmbTextListToTextProperty(Display*, char**, int, XICCEncodingStyle, XTextProperty*)
Kill Thread
```
Crash in `_x_text_decode` ("debugger("Unhandled encoding!");").

**Comment by waddlesplash** [comment]
Probably it used to work "by accident" since I just treated unhandled encodings as UTF-8. I'll re-build it and add some better debugging information.

It also seems to really want ISO8859 text. Not sure what to do about that one, I was kind of hoping applications would generally tolerate Unicode.

**Comment by X547** [comment]
It run if remove `debugger("Unhandled encoding!");`.

**Comment by waddlesplash** [comment]
Fixed again.
