### ISSUE TITLE
fontforge

### ISSUE THREAD

**Issue by xor256** [waddlesplash/xlibe#11]
font forge will be compiled?

**Comment by waddlesplash** [comment]
It compiles and starts but does not work quite right last I checked; it got "stalled" after not a lot of input. However that was before some of the more recent rounds of mouse event fixes, so maybe it would do better these days, I didn't really spend much time on it.

**Comment by waddlesplash** [comment]
It seems recent FontForge has a GDK backend, that should probably be used instead of the X11 one, as it will function more reliably, I'd expect.
