### ISSUE TITLE
Icon Programming Languages

### ISSUE THREAD

**Issue by agrellum** [waddlesplash/xlibe#12]
Very happy with xlibe.

With some quirks, Classic Icon working with xlibe.

See this post.

https://list.arizona.edu/sympa/arc/icon-language/2022-07/msg00005.html

Also the the svn version of Object Icon builds and runs well without xlibe.

See this site.

http://objecticon.sourceforge.net/

Thank you.

**Comment by waddlesplash** [comment]
I fixed some of the quirks and replied to the mailing list with some details. Thanks for using Haiku (and Xlibe)!
